### ISSUE TITLE
Issue with Gravity Turn mod

### ISSUE THREAD

**Issue by joelmeaders** [allista/hangar#198] opened 2018-09-08 05:09 UTC
I'm using gravity turn 1.7.7 and the latest KSP and whenever it pops the fairing (aerodynamic hanger) the screen goes into some mode without a UI. Pressing Esc bring the UI back but there is no way to gain control of the vessel that came from the fairing. This has also happened a couple times via manual staging by space bar without gravity turn.

I tried it with various ships and the only sure way I can control the craftt that comes from the fairing is by right clicking the fairing and selecting "jettison payload".

Can anyone else recreate this?

**Comment by allista** [comment] 2018-09-08 13:49
Thanks for the report.
Could you please attach the output_log.txt (Player.log on mac/linux) after the bug happens? This looks like NRE. Also, double-check Hangar and AT_Utils versions against your KSP version.

**Comment by joelmeaders** [comment] 2018-09-09 05:43
For whatever reason my output log is 0kb in both 64bit and 32bit. I built a new launcher and minimal lander to test with and the same thing happened, but the ship didn't despawn and it gave me control after about 10 seconds. I'll put some more observations below.

Versions:
KSP x64 (1.4.5.2243) - Using -single-instance -force-opengl arguments on shortcut
Hangar (3.3.4.3)
AT_Utils (1.6.0.1)

I do not believe this is gravity turn anymore as it also happens when manually staging with gravity turn off. Kerbal portraits all black when the bug hits and they cannot EVA (says no hatch). When the bug hits the vessel is still attached but nothing on it highlights or can be selected. Mouse cannot be used to control camera.

I deleted my 0kb logs and I will try again tomorrow. I'll make a new sandbox game with minimal mods to try and recreate as well.

**Comment by allista** [comment] 2018-09-10 12:37
BTW, I'm still unable to reproduce it on my side.

**Comment by joelmeaders** [comment] 2018-09-14 01:08
I've been unable to reproduce it with a minimal mod install so it has to be one of the other mods I'm using that's causing a conflict somehow. While trying to figure out causes I had a rescue mission Kerbal spawn in the aerodynamic hangar lol. If I ever do figure it out i'll let you know.

**Comment by allista** [comment] 2019-07-16 07:54
Closing for now as unreproducible

**Closed** 2019-07-16 07:54 UTC
Labels: Unconfirmed, bug
