### ISSUE TITLE
TAC Life Support' Support

### ISSUE THREAD

**Issue by m9731526** [allista/hangar#174] opened 2016-10-23 05:15 UTC
If a TAC LS part and a kerbal is inside a fairing hangar, then the TAC system will warn life support supplies depleted at launch.

**Comment by allista** [comment] 2016-10-23 07:22
Thanks for the report!
I'll try to automate this somehow.
But for now a simple solution is to also add another LS container to the ship with the fairings.

**Comment by allista** [comment] 2016-10-27 08:35
Duplicate of #129

**Closed** 2016-11-13 17:27 UTC
Labels: enhancement
