### ISSUE TITLE
Having Trouble Jettisoning Payload

### ISSUE THREAD

**Issue by m9731526** [allista/hangar#172] opened 2016-10-21 23:20 UTC
Sometimes I'll encounter some issue to spawn stored ship successfully, but save before jettisoning and reload sometimes fix it. But this time I just can't jettison a ship mainly consist of RocketPart Containers and a Orbital Construction Dock from the Extraplanetery Laucnhpad mod.

I'm not sure if it's related to the EL mod, though.

I found this in output.log:

> NullReferenceException
>   at (wrapper managed-to-native) UnityEngine.Transform:INTERNAL_get_rotation (UnityEngine.Quaternion&)
>   at UnityEngine.Transform.get_rotation () [0x00000] in <filename unknown>:0 
>   at Vessel.SetPosition (Vector3d position, Boolean usePristineCoords) [0x00000] in <filename unknown>:0 
>   at Vessel.SetPosition (Vector3d position) [0x00000] in <filename unknown>:0 
>   at AtHangar.HangarMachinery+<launch_vessel>c__Iterator1.MoveNext () [0x00000] in <filename unknown>:0 
>   at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 

and

> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> [Part]: PartModule PropsUpdater at FairingsOcto, index 16: index exceeds module count as defined in cfg.
> Looking for PropsUpdater in other indices...
> 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> ...no PropsUpdater module found on part definition. Skipping...
> 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> PartModule is null.

Hope that helps.

**Comment by m9731526** [comment] 2016-10-22 04:49
I'm guessing that loaded part counts may be a factor of this... since I haven't successfully jettison one near my station.

**Comment by allista** [comment] 2016-10-22 07:15
Thanks for the report!
Could you share a savegame or a .craft file for me to test?

**Comment by m9731526** [comment] 2016-10-23 05:16
Sure.

[Station_ConstructionDock.zip](https://github.com/allista/hangar/files/546186/Station_ConstructionDock.zip)

**Comment by allista** [comment] 2016-10-25 15:08
I was unable to reproduce this exact exception, but I did found a bug with vessel positioning on launch from hangar. With it fixed I am now able to launch the provided Station from the Hangar Fairings in Kerbin, Mun and Duna orbits.
I will leave the issue open so that when I make a release you can test it and report back.

**Comment by allista** [comment] 2016-10-27 08:34
Should be fixed in v3.0.1.

**Closed** 2017-01-24 23:00 UTC
Labels: bug
