### ISSUE TITLE
When unloading a rover, it is uncontrollable

### ISSUE THREAD

**Issue by Whiffysole** [allista/hangar#148] opened 2015-01-11 06:17 UTC
On the Hangar Lander, once I unload a rover it is uncontrollable. I select control from here and nothing happens. And all the wheels break after it rolls out.

**Comment by allista** [comment] 2015-01-11 14:12
Please, supply **output_log.txt** (or Player.log if you're on Linux), two quicksaves -- before the rover is unloaded and after that -- and the name of the vessel in question.

**Comment by Whiffysole** [comment] 2015-01-11 19:04
The name of the rover is Basic Rover, and the hangar is named Hangar Lander.

Sorry if I did this wrong, I'm kind of a noob when it comes to this.




I found 5 output_log files, which one should I use?
![screenshot 1](https://cloud.githubusercontent.com/assets/10483202/5696338/9dbaaaf6-9981-11e4-8884-eaa2cd9f21b3.png)

**Comment by allista** [comment] 2015-01-11 23:22
The last one modified, which should be located in
`steamapps\common\Kerbal Space Program\KSP_Data`
**This is the file that is overwritten each time you launch the game**. So it will contain all the messages from the last run. Thus you need to run the game, load the needed save, recreate the problem, then quit and then publish this file (on Dropbox, Google Drive, Pastebin, etc...)

And your savegames (files with .sfs extension) are located in
`steamapps\common\Kerbal Space Program\saves\{you-savegame-name}\`
The main one is called persistant.sfs, others are quicksaves.

**Comment by Whiffysole** [comment] 2015-02-09 21:09
Sorry for the late reply. I didn't have much freetime recently. I am going
to get the file for you by the end of today.

**Comment by Whiffysole** [comment] 2015-02-09 21:13
I've also been procrastinating. :\

**Comment by allista** [comment] 2015-02-09 22:13
Tell me about it! =)
Ah, and you probably want to update to the new version before you start testing again.

**Comment by Whiffysole** [comment] 2015-02-10 01:36
https://drive.google.com/open?id=0By_MY7gQ3lDufnRabk9jX1Etc3pRRkJ2eFVLa2c0UnFTem8xQUNZTC1YN1lLb08xN3ZFak0&authuser=0
>
>
Here's the link. I hope this is what you needed.

**Comment by allista** [comment] 2015-02-10 10:12
First of all, you shouldn't have several ModuleManager dlls in your GameData. Leave only the latest version and remove the others.

Second, you have many problems with different mods. I see null reference exceptions from: LazorSystem, ProceduralParts and some class named KConfigDocumentationGenerator; don't know what that is.

**Last but not least**: the source of the problem with the Hangar is the conflict with **BetterBuoyancy**. Current version of BB (v1.1) has this problem fixed, so you need to update BB, and the problem should go.

**Comment by Whiffysole** [comment] 2015-02-10 22:02
Ok, thanks!

**Comment by allista** [comment] 2015-02-13 08:43
I presume the issue is indeed fixed, so I close it.

**Closed by allista** 2015-02-13 08:43 UTC
Labels: bug, Unconfirmed
